name: Reusable publish documentation

on:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
  publish_docs:
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent "race-condition" in publishing a new version of doc to `gh-pages`
    concurrency:
      group: on-docs-rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python Project
        uses: xyngular/reusable-github-workflows/py-setup-project@main
      - name: Ensure on latest branch
        run: |
          git config pull.rebase true
#          git config remote.origin.url >&- || git remote add origin https://github.com/"$ORIGIN"
          git pull origin main
      - name: Retrieve Project Version
        run: |
          PY_OUTPUT=$(poetry run python -c "import tomlkit; import pathlib; print(tomlkit.parse(pathlib.Path('pyproject.toml').read_text())['tool']['poetry']['version'], end='')")
          echo "VERSION=$PY_OUTPUT" >> $GITHUB_ENV
      - name: Retrieve Project Package
        run: |
          PY_OUTPUT=$(poetry run python -c "import tomlkit; import pathlib; print(tomlkit.parse(pathlib.Path('pyproject.toml').read_text())['tool']['poetry']['name'], end='')")
          echo "PY_PKG=$PY_OUTPUT" >> $GITHUB_ENV
      - name: Retrieve Project Module
        run: |
          PY_OUTPUT=$(poetry run python -c "import tomlkit; import pathlib; print(tomlkit.parse(pathlib.Path('pyproject.toml').read_text())['tool']['poetry']['packages'][0]['include'], end='')")
          echo "PY_MODULE=$PY_OUTPUT" >> $GITHUB_ENV
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs Deploy
          git config --global user.email docs@dummy.bot.orr.blue
      - name: Remove Any Previous Site/Api Docs
        run: rm -rf site api
      - name: Building Website Docs
        run: poetry run mike deploy --push --update-aliases ${{ env.VERSION }} latest

      - name: Building Api Ref Docs
        run: poetry run pdoc --html --output-dir ./api/ ./${{ env.PY_MODULE }} --force --config='show_inherited_members=True'

      - name: Release API docs
        uses: peaceiris/actions-gh-pages@v3
        env:
          VERSION: ${{ inputs.version }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
#          keep_files: true
          destination_dir: ${{ env.VERSION }}/api

      - name: Release API docs to latest
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
#          keep_files: true
          destination_dir: latest/api
